name: Local Config
version: 1.0.0
schema: v1

models:
  - name: 9router
    provider: openai
    model: cx/gpt-5.4
    apiBase: https://r5hrir4.9router.com/v1
    apiKey: sk-fafc424b97b0f0c3-7bf6u3-41a4c20d
    useResponsesApi: false
